name: Postman Data-Driven Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Loại test muốn chạy'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - post
        - get
        - delete

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test_data: [post, get, delete]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Newman CLI
      run: npm install -g newman
      
    - name: Run Authentication First
      run: |
        # Chạy authentication trước để lấy token
        newman run "Favorite API Tests - Data Driven.postman_collection.json" \
          -e "Favorite API Environment.postman_environment.json" \
          --folder "Authentication" \
          --reporters cli \
          --silent
          
    - name: Run Postman Tests
      run: |
        # Chạy tests theo loại (post/get/delete)
        if [ "${{ matrix.test_data }}" = "post" ]; then
          newman run "Favorite API Tests - Data Driven.postman_collection.json" \
            -e "Favorite API Environment.postman_environment.json" \
            --folder "Add Favorite" \
            --iteration-data "data/${{ matrix.test_data }}_favorite_test_data.csv" \
            --reporters cli,junit \
            --reporter-junit-export "${{ matrix.test_data }}_results.xml" \
            --bail
        elif [ "${{ matrix.test_data }}" = "get" ]; then
          newman run "Favorite API Tests - Data Driven.postman_collection.json" \
            -e "Favorite API Environment.postman_environment.json" \
            --folder "Get Favorites" \
            --iteration-data "data/${{ matrix.test_data }}_favorite_test_data.csv" \
            --reporters cli,junit \
            --reporter-junit-export "${{ matrix.test_data }}_results.xml" \
            --bail
        elif [ "${{ matrix.test_data }}" = "delete" ]; then
          newman run "Favorite API Tests - Data Driven.postman_collection.json" \
            -e "Favorite API Environment.postman_environment.json" \
            --folder "Delete Favorite" \
            --iteration-data "data/${{ matrix.test_data }}_favorite_test_data.csv" \
            --reporters cli,junit \
            --reporter-junit-export "${{ matrix.test_data }}_results.xml" \
            --bail
        fi
          
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: "${{ matrix.test_data }}-test-results"
        path: "${{ matrix.test_data }}_results.xml"
        
    # Note: Publish test results step removed due to GitHub permissions
    # Test results are available as artifacts for download 